from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
from collections import OrderedDict
from dataclasses import dataclass, field
from typing import Iterable, List


SECTION_HEADER_RE = re.compile(r"^## --- (?P<title>.+?) ---\s*$", re.MULTILINE)
ITEM_BLOCK_RE = re.compile(r"(?=^### (?:Class|Function): )", re.MULTILINE)
ITEM_NAME_RE = re.compile(r"^### (?:Class|Function): (?P<name>[^\s]+)", re.MULTILINE)
DEFAULT_INPUT_FILENAME = "all_api.md"
DEFAULT_OUTPUT_DIRNAME = "api"


@dataclass
class ModuleDoc:
    name: str
    items: "OrderedDict[str, str]" = field(default_factory=OrderedDict)


@dataclass
class WarningDoc:
    title: str
    body: str = ""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Summarize raw API extract markdown into per-module knowledge-base files."
    )
    parser.add_argument(
        "input_md",
        nargs="?",
        default=None,
        help="Optional path to raw markdown generated by extra.py. Defaults to all_api.md beside this script.",
    )
    parser.add_argument(
        "output_dir",
        nargs="?",
        default=None,
        help="Optional output directory. Defaults to api/ beside this script.",
    )
    return parser.parse_args()


def script_dir() -> str:
    return os.path.dirname(os.path.abspath(__file__))


def resolve_input_path(input_md: str | None) -> str:
    if input_md:
        return input_md

    default_input = os.path.join(script_dir(), DEFAULT_INPUT_FILENAME)
    if os.path.exists(default_input):
        return default_input

    print(
        "Error: 未提供输入文件，且默认输入文件不存在。"
        f" 期望默认文件: '{default_input}'。"
        " 请传入输入文件路径，例如: python3 summary.py /path/to/all_api.md",
        file=sys.stderr,
    )
    sys.exit(1)


def resolve_output_dir(output_dir: str | None) -> str:
    if output_dir:
        return output_dir
    return os.path.join(script_dir(), DEFAULT_OUTPUT_DIRNAME)


def read_text(path: str) -> str:
    if not os.path.exists(path):
        print(f"Error: 找不到输入文件 '{path}'", file=sys.stderr)
        sys.exit(1)
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def iter_sections(content: str) -> Iterable[tuple[str, str]]:
    matches = list(SECTION_HEADER_RE.finditer(content))
    for idx, match in enumerate(matches):
        start = match.end()
        end = matches[idx + 1].start() if idx + 1 < len(matches) else len(content)
        yield match.group("title").strip(), content[start:end].strip()


def split_item_blocks(section_text: str) -> List[str]:
    blocks: List[str] = []
    for block in ITEM_BLOCK_RE.split(section_text):
        block = block.strip()
        if block.startswith("### "):
            blocks.append(block)
    return blocks


def parse_modules(content: str) -> "OrderedDict[str, ModuleDoc]":
    modules: "OrderedDict[str, ModuleDoc]" = OrderedDict()

    for section_title, section_text in iter_sections(content):
        if not section_title.startswith("模块: "):
            continue
        module_name = section_title[len("模块: ") :].strip()
        module_doc = modules.setdefault(module_name, ModuleDoc(name=module_name))
        for block in split_item_blocks(section_text):
            match = ITEM_NAME_RE.match(block)
            if match is None:
                continue
            item_name = match.group("name")
            old_block = module_doc.items.get(item_name)
            if old_block is None or len(block) > len(old_block):
                module_doc.items[item_name] = block

    return modules


def parse_warning_doc(content: str) -> WarningDoc | None:
    for section_title, section_text in iter_sections(content):
        if section_title == "导入警告" and section_text:
            return WarningDoc(title=section_title, body=section_text)
    return None


def safe_filename(module_name: str) -> str:
    return f"{module_name.replace('.', '_').replace('/', '_')}.md"


def render_module_doc(module_doc: ModuleDoc) -> str:
    lines = [f"# 模块: {module_doc.name}", ""]
    if not module_doc.items:
        lines.append("_No public classes/functions discovered in this module._")
        lines.append("")
        return "\n".join(lines)

    for item_name, block in module_doc.items.items():
        lines.append(block)
        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_warning_doc(warning_doc: WarningDoc) -> str:
    return f"# {warning_doc.title}\n\n{warning_doc.body.rstrip()}\n"


def prepare_output_dir(output_dir: str) -> None:
    if os.path.exists(output_dir):
        if not os.path.isdir(output_dir):
            print(f"Error: 输出路径 '{output_dir}' 已存在且不是文件夹。", file=sys.stderr)
            sys.exit(1)
        shutil.rmtree(output_dir)
    os.makedirs(output_dir, exist_ok=True)


def write_outputs(
    modules: "OrderedDict[str, ModuleDoc]",
    output_dir: str,
    warning_doc: WarningDoc | None = None,
) -> None:
    prepare_output_dir(output_dir)

    index_lines = [
        "# PyQUDA Agent 知识库索引",
        "**说明**: 本目录包含了按原始模块层级整理后的 PyQUDA 接口调用约定。",
        "",
    ]

    total_items = 0
    for module_name, module_doc in modules.items():
        filename = safe_filename(module_name)
        output_path = os.path.join(output_dir, filename)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(render_module_doc(module_doc))
        item_count = len(module_doc.items)
        total_items += item_count
        index_lines.append(f"- **[{module_name}]({filename})** - 包含 {item_count} 个接口")

    if warning_doc is not None:
        warning_filename = "import_warnings.md"
        warning_path = os.path.join(output_dir, warning_filename)
        with open(warning_path, "w", encoding="utf-8") as f:
            f.write(render_warning_doc(warning_doc))
        index_lines.append(f"- **[导入警告]({warning_filename})** - 环境依赖/兼容性警告汇总")

    index_path = os.path.join(output_dir, "index.md")
    with open(index_path, "w", encoding="utf-8") as f:
        f.write("\n".join(index_lines) + "\n")

    print(f"成功: 数据已清洗去重，共处理 {total_items} 个独立接口，输出至目录 '{output_dir}'")
    print(f"入口点已生成: {index_path}")


def parse_and_summarize(input_filepath: str, output_dir: str) -> None:
    content = read_text(input_filepath)
    modules = parse_modules(content)
    warning_doc = parse_warning_doc(content)
    if not modules:
        print("Warning: 未能在输入文件中解析到任何模块块。请检查输入格式。", file=sys.stderr)
        return
    write_outputs(modules, output_dir, warning_doc)


def main() -> None:
    args = parse_args()
    input_filepath = resolve_input_path(args.input_md)
    output_dir = resolve_output_dir(args.output_dir)
    parse_and_summarize(input_filepath, output_dir)


if __name__ == "__main__":
    main()
